### ISSUE TITLE
[MNT] remove mutable defaults from constructors, methods, and functions

### ISSUE THREAD

**Issue by fkiraly** [NorskRegnesentral/skchange#42]
We should remove mutable defaults from constructors, methods, and functions - this is a general pytho "don't do this".

An example is `change_score=L2Cost()` in many places - if we call a mutating `set_params` on the object, it will change the default for all newly constructed estimators!

Afaik this can also be automatically checked, I believe the `sktime` CI does this, but only on repository level (not `check_estimator`).

**Comment by Tveten** [comment]
Aha, good point. Thanks for the tip! I'll work on a fix.

**Comment by Tveten** [comment]
What is the best solution for dealing with such cases?

1. Remove the default.
2. Set default = None and document what None means.
3. Use "str" inputs + a string-to-class factory that creates the scorer class from the string

I'm leaning towards 1. since the cost/score parameter is something that really should be selected by the user. This is the parameter that governs what type of data characteristic you are looking for a change in. Looking for changes in the mean (L2Cost) is typical though, but I think users should be forced to explore the options and understand it.

Very open to be convinced otherwise.

**Comment by fkiraly** [comment]
I think the best way is 2, because it keeps sensible defaults and is also deprecation safe.

I consider no.2 the "standard" in having mutable defaults, the pattern being

```
def __init__(param=None):
    self.param = param
    self._param = param if param else param_default

def later(self, x, y, z):
    use(self._param)
```

**Comment by Tveten** [comment]
Alright.

What is the appropriate way of documenting this?

1. 
```
class DummyDetector
"""
change_score : BaseChangeScore or BaseCost, default = `L2Cost`
"""

def __init__(change_score = None):
```

2.
```
class DummyDetector
"""
change_score : BaseChangeScore,  BaseCost or None, default = None
    ... If `change_score` is None, it defaults to an `L2Cost`.
"""

def __init__(change_score = None):
```
